# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/facun/OneDrive/Desktop/Diseño Digital Avanzado/Unit01/sr_muxVioIla/shiftReg/Arty_Master_v2.xdc

# Block Designs: bd/ILA/ILA.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ILA || ORIG_REF_NAME==ILA} -quiet] -quiet

# IP: bd/ILA/ip/ILA_ila_0_0/ILA_ila_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ILA_ila_0_0 || ORIG_REF_NAME==ILA_ila_0_0} -quiet] -quiet

# Block Designs: bd/VIO/VIO.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==VIO || ORIG_REF_NAME==VIO} -quiet] -quiet

# IP: bd/VIO/ip/VIO_vio_0_0/VIO_vio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==VIO_vio_0_0 || ORIG_REF_NAME==VIO_vio_0_0} -quiet] -quiet

# XDC: c:/Users/facun/vivadoProjects/Lab01/Lab01.gen/sources_1/bd/ILA/ILA_ooc.xdc

# XDC: c:/Users/facun/vivadoProjects/Lab01/Lab01.gen/sources_1/bd/VIO/VIO_ooc.xdc
